from django.contrib import admin

# Import Models to Register
from .models import Category, Product


# Register Categories in Admin
@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ["name", "slug"]
    prepopulated_fields = {"slug": ("name",)}


# Register Products in Admin
@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    list_display = ["name", "slug", "price", "available", "created", "updated"]
    list_filter = ["available", "created", "updated"]
    list_editable = ["price", "available"]  # This field can be edit in List-View
    prepopulated_fields = {
        "slug": ("name",)
    }  # Generated, slug field generated by name field
